"""Generate Foundry fuzz test harnesses for audit targets."""

from __future__ import annotations

import re
from pathlib import Path


def generate_fuzz_harness(
    contract_name: str,
    functions: list[dict],
    output_dir: Path,
) -> Path:
    """Generate a Foundry fuzz test harness for a contract.

    Args:
        contract_name: Name of the contract to fuzz
        functions: List of function dicts with {name, inputs, stateMutability}
        output_dir: Directory to write the test file

    Returns:
        Path to the generated test file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    test_file = output_dir / f"Fuzz{contract_name}.t.sol"

    function_tests = []
    for fn in functions:
        if fn.get("stateMutability") in ("view", "pure"):
            continue
        fn_name = fn.get("name", "")
        if not fn_name or fn_name.startswith("_"):
            continue

        params = _build_params(fn.get("inputs", []))
        param_names = [p.split()[-1] for p in params] if params else []

        function_tests.append(f"""
    function testFuzz_{fn_name}({', '.join(params)}) public {{
        try target.{fn_name}({', '.join(param_names)}) {{
            // Should not revert unexpectedly
        }} catch {{
            // Expected reverts are acceptable
        }}
    }}""")

    content = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/{contract_name}.sol";

/// @title Fuzz test harness for {contract_name}
/// @notice Auto-generated by contract-audit
contract Fuzz{contract_name}Test is Test {{
    {contract_name} target;

    function setUp() public {{
        target = new {contract_name}();
    }}
{''.join(function_tests)}

    /// @notice Invariant: contract ETH balance should not decrease unexpectedly
    function invariant_ethBalance() public {{
        uint256 balance = address(target).balance;
        // Add protocol-specific invariants here
        assertTrue(balance >= 0, "Balance invariant");
    }}
}}
"""
    test_file.write_text(content)
    return test_file


def _build_params(inputs: list[dict]) -> list[str]:
    """Build Solidity parameter declarations from ABI inputs."""
    params = []
    for inp in inputs:
        type_ = _map_type(inp.get("type", "uint256"))
        name = inp.get("name", f"param{len(params)}")
        params.append(f"{type_} {name}")
    return params


def _map_type(solidity_type: str) -> str:
    """Map Solidity ABI types to fuzz-friendly types."""
    type_map = {
        "uint": "uint256",
        "int": "int256",
        "bool": "bool",
        "address": "address",
        "bytes": "bytes",
        "string": "string",
    }
    for prefix, mapped in type_map.items():
        if solidity_type.startswith(prefix):
            return solidity_type
    return solidity_type
