"""Generate Foundry fuzz test harnesses for audit targets."""

from __future__ import annotations

import re
from pathlib import Path


def generate_fuzz_harness(
    contract_name: str,
    functions: list[dict],
    output_dir: Path,
) -> Path:
    """Generate a Foundry fuzz test harness for a contract.

    Args:
        contract_name: Name of the contract to fuzz
        functions: List of function dicts with {name, inputs, stateMutability}
        output_dir: Directory to write the test file

    Returns:
        Path to the generated test file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    test_file = output_dir / f"Fuzz{contract_name}.t.sol"

    function_tests = []
    for fn in functions:
        if fn.get("stateMutability") in ("view", "pure"):
            continue
        fn_name = fn.get("name", "")
        if not fn_name or fn_name.startswith("_"):
            continue

        params = _build_params(fn.get("inputs", []))
        param_names = [p.split()[-1] for p in params] if params else []

        function_tests.append(f"""
    function testFuzz_{fn_name}({', '.join(params)}) public {{
        try target.{fn_name}({', '.join(param_names)}) {{
            // Should not revert unexpectedly
        }} catch {{
            // Expected reverts are acceptable
        }}
    }}""")

    content = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/{contract_name}.sol";

/// @title Fuzz test harness for {contract_name}
/// @notice Auto-generated by contract-audit
contract Fuzz{contract_name}Test is Test {{
    {contract_name} target;

    function setUp() public {{
        target = new {contract_name}();
    }}
{''.join(function_tests)}

    /// @notice Invariant: contract ETH balance should not decrease unexpectedly
    function invariant_ethBalance() public {{
        uint256 balance = address(target).balance;
        // Add protocol-specific invariants here
        assertTrue(balance >= 0, "Balance invariant");
    }}
}}
"""
    test_file.write_text(content)
    return test_file


def _build_params(inputs: list[dict]) -> list[str]:
    """Build Solidity parameter declarations from ABI inputs."""
    params = []
    for inp in inputs:
        type_ = _map_type(inp.get("type", "uint256"))
        name = inp.get("name", f"param{len(params)}")
        params.append(f"{type_} {name}")
    return params


def _map_type(solidity_type: str) -> str:
    """Map Solidity ABI types to fuzz-friendly types."""
    type_map = {
        "uint": "uint256",
        "int": "int256",
        "bool": "bool",
        "address": "address",
        "bytes": "bytes",
        "string": "string",
    }
    for prefix, mapped in type_map.items():
        if solidity_type.startswith(prefix):
            return solidity_type
    return solidity_type


# --- Finding-based targeted harness generation ---

_CATEGORY_TEMPLATES: dict[str, str] = {
    "reentrancy": """
    /// @notice Test reentrancy via callback
    function test_reentrancy_{fn}() public {{
        // Setup attacker contract that re-enters during callback
        vm.prank(attacker);
        try target.{fn}({args}) {{
            // Check if state was corrupted by reentrancy
        }} catch {{}}
    }}""",
    "arithmetic": """
    /// @notice Test arithmetic boundary values
    function test_arithmetic_{fn}() public {{
        // Test with 0
        try target.{fn}(0{extra_zeros}) {{}} catch {{}}
        // Test with max uint
        try target.{fn}(type(uint256).max{extra_max}) {{}} catch {{}}
        // Test with 1
        try target.{fn}(1{extra_ones}) {{}} catch {{}}
    }}""",
    "access-control": """
    /// @notice Test unauthorized access
    function test_unauthorized_{fn}() public {{
        address unauthorized = address(0xdead);
        vm.prank(unauthorized);
        try target.{fn}({args}) {{
            // If this succeeds, access control is missing
            revert("Unauthorized call should have reverted");
        }} catch {{
            // Expected: unauthorized call reverts
        }}
    }}""",
}


def generate_targeted_harness(
    contract_name: str,
    finding: "Any",
    source: str,
    output_dir: Path,
) -> Path:
    """Generate a targeted fuzz test based on a specific finding.

    Args:
        contract_name: Name of the vulnerable contract
        finding: Finding object with category and location
        source: Contract source code
        output_dir: Directory to write test file

    Returns:
        Path to the generated test file
    """
    from ...core.models import FindingCategory

    output_dir.mkdir(parents=True, exist_ok=True)

    category_key = finding.category.value
    func_name = ""
    if finding.locations:
        func_name = finding.locations[0].function or "target"

    # Select template based on category
    template_key = "reentrancy"
    if finding.category in (FindingCategory.ARITHMETIC,):
        template_key = "arithmetic"
    elif finding.category in (FindingCategory.ACCESS_CONTROL,):
        template_key = "access-control"
    elif finding.category in (FindingCategory.REENTRANCY,):
        template_key = "reentrancy"

    template = _CATEGORY_TEMPLATES.get(template_key, _CATEGORY_TEMPLATES["reentrancy"])

    # Build test body
    safe_fn = re.sub(r'[^a-zA-Z0-9_]', '_', func_name)
    test_body = template.format(
        fn=safe_fn,
        args="",
        extra_zeros="",
        extra_max="",
        extra_ones="",
    )

    test_file = output_dir / f"Targeted_{contract_name}_{safe_fn}.t.sol"

    content = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/{contract_name}.sol";

/// @title Targeted test for {finding.title}
/// @notice Auto-generated by contract-audit based on finding
contract Targeted_{contract_name}_{safe_fn}_Test is Test {{
    {contract_name} target;
    address attacker = address(0xBEEF);

    function setUp() public {{
        target = new {contract_name}();
        vm.deal(attacker, 100 ether);
    }}
{test_body}
}}
"""
    test_file.write_text(content)
    return test_file
