"""Invariant test generator for Foundry.

Automatically detects common invariants based on contract patterns
(ERC20, vault, ownable, etc.) and generates Foundry invariant tests.
"""

from __future__ import annotations

import re
from pathlib import Path

# Pattern -> invariant mapping
INVARIANT_PATTERNS: list[dict[str, str]] = [
    {
        "name": "erc20_supply",
        "detect": r'\btotalSupply\b.*\bbalanceOf\b|\bbalanceOf\b.*\btotalSupply\b',
        "description": "ERC20 total supply equals sum of all balances",
        "test": """
    /// @notice totalSupply should always equal sum of tracked balances
    function invariant_totalSupplyConsistency() public {{
        // totalSupply should never underflow or overflow unexpectedly
        assertTrue(target.totalSupply() >= 0, "totalSupply >= 0");
    }}""",
    },
    {
        "name": "vault_assets",
        "detect": r'\btotalAssets\b.*\btotalSupply\b|\bshares\b.*\bassets\b',
        "description": "Vault total assets >= total shares (no inflation)",
        "test": """
    /// @notice totalAssets should maintain consistency with shares
    function invariant_vaultAssetsConsistency() public {{
        if (target.totalSupply() > 0) {{
            assertTrue(
                target.totalAssets() > 0,
                "Non-zero shares should mean non-zero assets"
            );
        }}
    }}""",
    },
    {
        "name": "ownable",
        "detect": r'\bowner\b.*\baddress\b|\bonlyOwner\b',
        "description": "Owner should never be address(0)",
        "test": """
    /// @notice Owner should never be zero address
    function invariant_ownerNotZero() public {{
        assertTrue(
            target.owner() != address(0),
            "Owner must not be zero address"
        );
    }}""",
    },
    {
        "name": "pausable",
        "detect": r'\bpaused\b.*\bwhenNotPaused\b|\bpause\b.*\bunpause\b',
        "description": "Paused state should block sensitive operations",
        "test": """
    /// @notice Paused contract state consistency
    function invariant_pauseConsistency() public {{
        // When paused, certain operations should revert
        // This is a basic check - extend with protocol specifics
    }}""",
    },
    {
        "name": "balance_conservation",
        "detect": r'\.transfer\s*\(|\bcall\s*\{.*value',
        "description": "ETH/token balance conservation",
        "test": """
    /// @notice Contract balance should be accounted for
    function invariant_balanceConservation() public {{
        uint256 balance = address(target).balance;
        // Balance should be tracked by internal accounting
        assertTrue(balance >= 0, "Balance conservation");
    }}""",
    },
]


def generate_invariant_tests(
    contract_name: str,
    source: str,
    output_dir: Path,
) -> Path:
    """Auto-detect invariants and generate Foundry invariant tests.

    Args:
        contract_name: Name of the target contract
        source: Solidity source code
        output_dir: Directory to write test file

    Returns:
        Path to the generated test file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    test_file = output_dir / f"Invariant{contract_name}.t.sol"

    # Detect which invariants apply
    applicable_tests = []
    for pattern in INVARIANT_PATTERNS:
        if re.search(pattern["detect"], source, re.IGNORECASE | re.DOTALL):
            applicable_tests.append(pattern)

    if not applicable_tests:
        # Add a basic no-revert invariant
        applicable_tests.append({
            "name": "no_unexpected_revert",
            "test": """
    /// @notice Basic liveness: contract should not self-destruct
    function invariant_contractExists() public {{
        assertTrue(
            address(target).code.length > 0,
            "Contract should still exist"
        );
    }}""",
        })

    test_bodies = "\n".join(t["test"] for t in applicable_tests)

    content = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/{contract_name}.sol";

/// @title Invariant tests for {contract_name}
/// @notice Auto-generated by contract-audit
contract Invariant{contract_name}Test is Test {{
    {contract_name} target;

    function setUp() public {{
        target = new {contract_name}();
    }}
{test_bodies}
}}
"""
    test_file.write_text(content)
    return test_file


def detect_invariants(source: str) -> list[str]:
    """Detect which invariant patterns apply to the given source.

    Returns:
        List of invariant pattern names that matched
    """
    matches = []
    for pattern in INVARIANT_PATTERNS:
        if re.search(pattern["detect"], source, re.IGNORECASE | re.DOTALL):
            matches.append(pattern["name"])
    return matches
