"""GitHub CI adapter: PR comments and SARIF upload."""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from typing import Any

from ..core.models import AuditResult, Severity

logger = logging.getLogger(__name__)


class GitHubAdapter:
    """Handles GitHub CI integration: PR comments and SARIF uploads."""

    def __init__(self) -> None:
        self.token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
        self.repo = os.environ.get("GITHUB_REPOSITORY")
        self.pr_number = os.environ.get("PR_NUMBER") or self._get_pr_number()

    def _get_pr_number(self) -> str | None:
        """Extract PR number from GitHub event context."""
        event_name = os.environ.get("GITHUB_EVENT_NAME")
        if event_name == "pull_request":
            import json
            event_path = os.environ.get("GITHUB_EVENT_PATH")
            if event_path and Path(event_path).exists():
                try:
                    event = json.loads(Path(event_path).read_text())
                    return str(event.get("number", ""))
                except Exception:
                    pass
        return None

    def post_pr_comment(self, result: AuditResult, report_content: str) -> bool:
        """Post audit summary as a PR comment using gh CLI."""
        if not self.pr_number:
            logger.info("No PR number found, skipping PR comment")
            return False

        if not self.token:
            logger.warning("No GITHUB_TOKEN, skipping PR comment")
            return False

        summary = result.summary
        comment = self._build_comment(result, report_content)

        try:
            proc = subprocess.run(
                [
                    "gh", "pr", "comment", self.pr_number,
                    "--body", comment,
                ],
                capture_output=True,
                text=True,
                timeout=30,
                env={**os.environ, "GH_TOKEN": self.token},
            )
            if proc.returncode == 0:
                logger.info(f"Posted PR comment on #{self.pr_number}")
                return True
            else:
                logger.warning(f"Failed to post PR comment: {proc.stderr}")
                return False
        except Exception as e:
            logger.warning(f"PR comment failed: {e}")
            return False

    def _build_comment(self, result: AuditResult, report_content: str) -> str:
        """Build a concise PR comment body."""
        s = result.summary
        score = s.overall_risk_score

        # Score emoji
        score_emoji = "🔴" if score >= 7 else "🟠" if score >= 4 else "🟢"

        lines = [
            "## 🔍 Smart Contract Audit Results",
            "",
            f"**Risk Score:** {score_emoji} **{score}/10**",
            "",
            "| Severity | Count |",
            "|----------|-------|",
        ]

        if s.critical_count > 0:
            lines.append(f"| 🔴 Critical | **{s.critical_count}** |")
        if s.high_count > 0:
            lines.append(f"| 🟠 High | **{s.high_count}** |")
        if s.medium_count > 0:
            lines.append(f"| 🟡 Medium | {s.medium_count} |")
        if s.low_count > 0:
            lines.append(f"| 🔵 Low | {s.low_count} |")
        if s.informational_count > 0:
            lines.append(f"| ⚪ Info | {s.informational_count} |")

        lines.extend(["", "### Top Findings", ""])

        # Top 5 critical/high findings
        for finding in result.active_findings[:5]:
            loc = finding.primary_location()
            loc_str = f"`{loc.file}:{loc.start_line}`" if loc else ""
            lines.append(
                f"- **[{finding.severity.value}]** {finding.title} {loc_str}"
            )

        lines.extend([
            "",
            "<details>",
            "<summary>View full report</summary>",
            "",
            report_content[:10000],  # Truncate if too long
            "",
            "</details>",
            "",
            "_Generated by [contract-audit](https://github.com/crytic/contract-audit)_",
        ])

        return "\n".join(lines)

    def get_ci_exit_code(self, result: AuditResult, config: Any) -> int:
        """Get the appropriate CI exit code based on findings."""
        if config.ci_fail_on_critical and result.summary.critical_count > 0:
            return 1
        if config.ci_fail_on_high and result.summary.high_count > 0:
            return 1
        return 0
